# Generated by Django 2.0 on 2022-07-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': '이미 있는 이름이네요!'}, max_length=12, unique=True)),
                ('coin', models.IntegerField()),
            ],
        ),
    ]
